/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResourceRouteImport } from './routes/_resource'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiPdfRouteImport } from './routes/api/pdf'
import { Route as ApiInvoicesRouteImport } from './routes/api/invoices'
import { Route as ApiExpensesRouteImport } from './routes/api/expenses'
import { Route as ApiExchangeRatesRouteImport } from './routes/api/exchange-rates'
import { Route as ApiClientsRouteImport } from './routes/api/clients'
import { Route as ResourceProjectsRouteImport } from './routes/_resource/projects'
import { Route as ResourceInvoicesRouteImport } from './routes/_resource/invoices'
import { Route as ResourceExpensesRouteImport } from './routes/_resource/expenses'
import { Route as ResourceClientsRouteImport } from './routes/_resource/clients'
import { Route as ResourceProjectsIndexRouteImport } from './routes/_resource/projects/index'
import { Route as ResourceInvoicesIndexRouteImport } from './routes/_resource/invoices/index'
import { Route as ResourceExpensesIndexRouteImport } from './routes/_resource/expenses/index'
import { Route as ResourceClientsIndexRouteImport } from './routes/_resource/clients/index'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiInvoicesIdRouteImport } from './routes/api/invoices/$id'
import { Route as ApiExpensesIdRouteImport } from './routes/api/expenses/$id'
import { Route as ApiExpenseHistoryOverviewRouteImport } from './routes/api/expense-history/overview'
import { Route as ApiExpenseHistoryMonthsRouteImport } from './routes/api/expense-history/months'
import { Route as ApiClientsIdRouteImport } from './routes/api/clients/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ResourceProjectsCreateRouteImport } from './routes/_resource/projects/create'
import { Route as ResourceInvoicesCreateRouteImport } from './routes/_resource/invoices/create'
import { Route as ResourceInvoicesIdRouteImport } from './routes/_resource/invoices/$id'
import { Route as ResourceExpensesHistoryRouteImport } from './routes/_resource/expenses/history'
import { Route as ResourceExpensesCreateRouteImport } from './routes/_resource/expenses/create'
import { Route as ResourceClientsCreateRouteImport } from './routes/_resource/clients/create'
import { Route as ApiExpenseHistoryTransactionsBatchRouteImport } from './routes/api/expense-history/transactions/batch'
import { Route as ApiExpenseHistoryTransactionsIdRouteImport } from './routes/api/expense-history/transactions/$id'
import { Route as ApiExpenseHistoryMonthsMonthRouteImport } from './routes/api/expense-history/months/$month'
import { Route as ApiExpenseHistoryImportPreviewRouteImport } from './routes/api/expense-history/import/preview'
import { Route as ApiExpenseHistoryImportCommitRouteImport } from './routes/api/expense-history/import/commit'
import { Route as ResourceProjectsEditIdRouteImport } from './routes/_resource/projects/edit/$id'
import { Route as ResourceProjectsCreateModalRouteImport } from './routes/_resource/projects/create.modal'
import { Route as ResourceExpensesEditIdRouteImport } from './routes/_resource/expenses/edit/$id'
import { Route as ResourceExpensesCreateModalRouteImport } from './routes/_resource/expenses/create.modal'
import { Route as ResourceClientsEditIdRouteImport } from './routes/_resource/clients/edit/$id'
import { Route as ResourceClientsCreateModalRouteImport } from './routes/_resource/clients/create.modal'
import { Route as ApiExpenseHistoryTransactionsIdExpenseRouteImport } from './routes/api/expense-history/transactions/$id/expense'
import { Route as ResourceProjectsEditIdModalRouteImport } from './routes/_resource/projects/edit.$id.modal'
import { Route as ResourceExpensesHistoryEditIdRouteImport } from './routes/_resource/expenses/history/edit/$id'
import { Route as ResourceExpensesHistoryCreateExpenseIdRouteImport } from './routes/_resource/expenses/history/create-expense/$id'
import { Route as ResourceExpensesEditIdModalRouteImport } from './routes/_resource/expenses/edit.$id.modal'
import { Route as ResourceClientsEditIdModalRouteImport } from './routes/_resource/clients/edit.$id.modal'
import { Route as ResourceExpensesHistoryEditIdModalRouteImport } from './routes/_resource/expenses/history/edit/$id/modal'
import { Route as ResourceExpensesHistoryCreateExpenseIdModalRouteImport } from './routes/_resource/expenses/history/create-expense/$id/modal'

const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceRoute = ResourceRouteImport.update({
  id: '/_resource',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesRoute = ApiExpensesRouteImport.update({
  id: '/api/expenses',
  path: '/api/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRatesRoute = ApiExchangeRatesRouteImport.update({
  id: '/api/exchange-rates',
  path: '/api/exchange-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceProjectsRoute = ResourceProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ResourceRoute,
} as any)
const ResourceInvoicesRoute = ResourceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ResourceRoute,
} as any)
const ResourceExpensesRoute = ResourceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ResourceRoute,
} as any)
const ResourceClientsRoute = ResourceClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ResourceRoute,
} as any)
const ResourceProjectsIndexRoute = ResourceProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourceProjectsRoute,
} as any)
const ResourceInvoicesIndexRoute = ResourceInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourceInvoicesRoute,
} as any)
const ResourceExpensesIndexRoute = ResourceExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourceExpensesRoute,
} as any)
const ResourceClientsIndexRoute = ResourceClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourceClientsRoute,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiInvoicesIdRoute = ApiInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiExpensesIdRoute = ApiExpensesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExpensesRoute,
} as any)
const ApiExpenseHistoryOverviewRoute =
  ApiExpenseHistoryOverviewRouteImport.update({
    id: '/api/expense-history/overview',
    path: '/api/expense-history/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExpenseHistoryMonthsRoute = ApiExpenseHistoryMonthsRouteImport.update({
  id: '/api/expense-history/months',
  path: '/api/expense-history/months',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsIdRoute = ApiClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceProjectsCreateRoute = ResourceProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ResourceProjectsRoute,
} as any)
const ResourceInvoicesCreateRoute = ResourceInvoicesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ResourceInvoicesRoute,
} as any)
const ResourceInvoicesIdRoute = ResourceInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResourceInvoicesRoute,
} as any)
const ResourceExpensesHistoryRoute = ResourceExpensesHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ResourceExpensesRoute,
} as any)
const ResourceExpensesCreateRoute = ResourceExpensesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ResourceExpensesRoute,
} as any)
const ResourceClientsCreateRoute = ResourceClientsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ResourceClientsRoute,
} as any)
const ApiExpenseHistoryTransactionsBatchRoute =
  ApiExpenseHistoryTransactionsBatchRouteImport.update({
    id: '/api/expense-history/transactions/batch',
    path: '/api/expense-history/transactions/batch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExpenseHistoryTransactionsIdRoute =
  ApiExpenseHistoryTransactionsIdRouteImport.update({
    id: '/api/expense-history/transactions/$id',
    path: '/api/expense-history/transactions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExpenseHistoryMonthsMonthRoute =
  ApiExpenseHistoryMonthsMonthRouteImport.update({
    id: '/$month',
    path: '/$month',
    getParentRoute: () => ApiExpenseHistoryMonthsRoute,
  } as any)
const ApiExpenseHistoryImportPreviewRoute =
  ApiExpenseHistoryImportPreviewRouteImport.update({
    id: '/api/expense-history/import/preview',
    path: '/api/expense-history/import/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExpenseHistoryImportCommitRoute =
  ApiExpenseHistoryImportCommitRouteImport.update({
    id: '/api/expense-history/import/commit',
    path: '/api/expense-history/import/commit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourceProjectsEditIdRoute = ResourceProjectsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ResourceProjectsRoute,
} as any)
const ResourceProjectsCreateModalRoute =
  ResourceProjectsCreateModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceProjectsCreateRoute,
  } as any)
const ResourceExpensesEditIdRoute = ResourceExpensesEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ResourceExpensesRoute,
} as any)
const ResourceExpensesCreateModalRoute =
  ResourceExpensesCreateModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceExpensesCreateRoute,
  } as any)
const ResourceClientsEditIdRoute = ResourceClientsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ResourceClientsRoute,
} as any)
const ResourceClientsCreateModalRoute =
  ResourceClientsCreateModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceClientsCreateRoute,
  } as any)
const ApiExpenseHistoryTransactionsIdExpenseRoute =
  ApiExpenseHistoryTransactionsIdExpenseRouteImport.update({
    id: '/expense',
    path: '/expense',
    getParentRoute: () => ApiExpenseHistoryTransactionsIdRoute,
  } as any)
const ResourceProjectsEditIdModalRoute =
  ResourceProjectsEditIdModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceProjectsEditIdRoute,
  } as any)
const ResourceExpensesHistoryEditIdRoute =
  ResourceExpensesHistoryEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => ResourceExpensesHistoryRoute,
  } as any)
const ResourceExpensesHistoryCreateExpenseIdRoute =
  ResourceExpensesHistoryCreateExpenseIdRouteImport.update({
    id: '/create-expense/$id',
    path: '/create-expense/$id',
    getParentRoute: () => ResourceExpensesHistoryRoute,
  } as any)
const ResourceExpensesEditIdModalRoute =
  ResourceExpensesEditIdModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceExpensesEditIdRoute,
  } as any)
const ResourceClientsEditIdModalRoute =
  ResourceClientsEditIdModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceClientsEditIdRoute,
  } as any)
const ResourceExpensesHistoryEditIdModalRoute =
  ResourceExpensesHistoryEditIdModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceExpensesHistoryEditIdRoute,
  } as any)
const ResourceExpensesHistoryCreateExpenseIdModalRoute =
  ResourceExpensesHistoryCreateExpenseIdModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceExpensesHistoryCreateExpenseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pdf': typeof PdfRoute
  '/clients': typeof ResourceClientsRouteWithChildren
  '/expenses': typeof ResourceExpensesRouteWithChildren
  '/invoices': typeof ResourceInvoicesRouteWithChildren
  '/projects': typeof ResourceProjectsRouteWithChildren
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/clients/create': typeof ResourceClientsCreateRouteWithChildren
  '/expenses/create': typeof ResourceExpensesCreateRouteWithChildren
  '/expenses/history': typeof ResourceExpensesHistoryRouteWithChildren
  '/invoices/$id': typeof ResourceInvoicesIdRoute
  '/invoices/create': typeof ResourceInvoicesCreateRoute
  '/projects/create': typeof ResourceProjectsCreateRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/expense-history/months': typeof ApiExpenseHistoryMonthsRouteWithChildren
  '/api/expense-history/overview': typeof ApiExpenseHistoryOverviewRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/clients/': typeof ResourceClientsIndexRoute
  '/expenses/': typeof ResourceExpensesIndexRoute
  '/invoices/': typeof ResourceInvoicesIndexRoute
  '/projects/': typeof ResourceProjectsIndexRoute
  '/clients/create/modal': typeof ResourceClientsCreateModalRoute
  '/clients/edit/$id': typeof ResourceClientsEditIdRouteWithChildren
  '/expenses/create/modal': typeof ResourceExpensesCreateModalRoute
  '/expenses/edit/$id': typeof ResourceExpensesEditIdRouteWithChildren
  '/projects/create/modal': typeof ResourceProjectsCreateModalRoute
  '/projects/edit/$id': typeof ResourceProjectsEditIdRouteWithChildren
  '/api/expense-history/import/commit': typeof ApiExpenseHistoryImportCommitRoute
  '/api/expense-history/import/preview': typeof ApiExpenseHistoryImportPreviewRoute
  '/api/expense-history/months/$month': typeof ApiExpenseHistoryMonthsMonthRoute
  '/api/expense-history/transactions/$id': typeof ApiExpenseHistoryTransactionsIdRouteWithChildren
  '/api/expense-history/transactions/batch': typeof ApiExpenseHistoryTransactionsBatchRoute
  '/clients/edit/$id/modal': typeof ResourceClientsEditIdModalRoute
  '/expenses/edit/$id/modal': typeof ResourceExpensesEditIdModalRoute
  '/expenses/history/create-expense/$id': typeof ResourceExpensesHistoryCreateExpenseIdRouteWithChildren
  '/expenses/history/edit/$id': typeof ResourceExpensesHistoryEditIdRouteWithChildren
  '/projects/edit/$id/modal': typeof ResourceProjectsEditIdModalRoute
  '/api/expense-history/transactions/$id/expense': typeof ApiExpenseHistoryTransactionsIdExpenseRoute
  '/expenses/history/create-expense/$id/modal': typeof ResourceExpensesHistoryCreateExpenseIdModalRoute
  '/expenses/history/edit/$id/modal': typeof ResourceExpensesHistoryEditIdModalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pdf': typeof PdfRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/clients/create': typeof ResourceClientsCreateRouteWithChildren
  '/expenses/create': typeof ResourceExpensesCreateRouteWithChildren
  '/expenses/history': typeof ResourceExpensesHistoryRouteWithChildren
  '/invoices/$id': typeof ResourceInvoicesIdRoute
  '/invoices/create': typeof ResourceInvoicesCreateRoute
  '/projects/create': typeof ResourceProjectsCreateRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/expense-history/months': typeof ApiExpenseHistoryMonthsRouteWithChildren
  '/api/expense-history/overview': typeof ApiExpenseHistoryOverviewRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/clients': typeof ResourceClientsIndexRoute
  '/expenses': typeof ResourceExpensesIndexRoute
  '/invoices': typeof ResourceInvoicesIndexRoute
  '/projects': typeof ResourceProjectsIndexRoute
  '/clients/create/modal': typeof ResourceClientsCreateModalRoute
  '/clients/edit/$id': typeof ResourceClientsEditIdRouteWithChildren
  '/expenses/create/modal': typeof ResourceExpensesCreateModalRoute
  '/expenses/edit/$id': typeof ResourceExpensesEditIdRouteWithChildren
  '/projects/create/modal': typeof ResourceProjectsCreateModalRoute
  '/projects/edit/$id': typeof ResourceProjectsEditIdRouteWithChildren
  '/api/expense-history/import/commit': typeof ApiExpenseHistoryImportCommitRoute
  '/api/expense-history/import/preview': typeof ApiExpenseHistoryImportPreviewRoute
  '/api/expense-history/months/$month': typeof ApiExpenseHistoryMonthsMonthRoute
  '/api/expense-history/transactions/$id': typeof ApiExpenseHistoryTransactionsIdRouteWithChildren
  '/api/expense-history/transactions/batch': typeof ApiExpenseHistoryTransactionsBatchRoute
  '/clients/edit/$id/modal': typeof ResourceClientsEditIdModalRoute
  '/expenses/edit/$id/modal': typeof ResourceExpensesEditIdModalRoute
  '/expenses/history/create-expense/$id': typeof ResourceExpensesHistoryCreateExpenseIdRouteWithChildren
  '/expenses/history/edit/$id': typeof ResourceExpensesHistoryEditIdRouteWithChildren
  '/projects/edit/$id/modal': typeof ResourceProjectsEditIdModalRoute
  '/api/expense-history/transactions/$id/expense': typeof ApiExpenseHistoryTransactionsIdExpenseRoute
  '/expenses/history/create-expense/$id/modal': typeof ResourceExpensesHistoryCreateExpenseIdModalRoute
  '/expenses/history/edit/$id/modal': typeof ResourceExpensesHistoryEditIdModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_resource': typeof ResourceRouteWithChildren
  '/login': typeof LoginRoute
  '/pdf': typeof PdfRoute
  '/_resource/clients': typeof ResourceClientsRouteWithChildren
  '/_resource/expenses': typeof ResourceExpensesRouteWithChildren
  '/_resource/invoices': typeof ResourceInvoicesRouteWithChildren
  '/_resource/projects': typeof ResourceProjectsRouteWithChildren
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/_resource/clients/create': typeof ResourceClientsCreateRouteWithChildren
  '/_resource/expenses/create': typeof ResourceExpensesCreateRouteWithChildren
  '/_resource/expenses/history': typeof ResourceExpensesHistoryRouteWithChildren
  '/_resource/invoices/$id': typeof ResourceInvoicesIdRoute
  '/_resource/invoices/create': typeof ResourceInvoicesCreateRoute
  '/_resource/projects/create': typeof ResourceProjectsCreateRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/expense-history/months': typeof ApiExpenseHistoryMonthsRouteWithChildren
  '/api/expense-history/overview': typeof ApiExpenseHistoryOverviewRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/_resource/clients/': typeof ResourceClientsIndexRoute
  '/_resource/expenses/': typeof ResourceExpensesIndexRoute
  '/_resource/invoices/': typeof ResourceInvoicesIndexRoute
  '/_resource/projects/': typeof ResourceProjectsIndexRoute
  '/_resource/clients/create/modal': typeof ResourceClientsCreateModalRoute
  '/_resource/clients/edit/$id': typeof ResourceClientsEditIdRouteWithChildren
  '/_resource/expenses/create/modal': typeof ResourceExpensesCreateModalRoute
  '/_resource/expenses/edit/$id': typeof ResourceExpensesEditIdRouteWithChildren
  '/_resource/projects/create/modal': typeof ResourceProjectsCreateModalRoute
  '/_resource/projects/edit/$id': typeof ResourceProjectsEditIdRouteWithChildren
  '/api/expense-history/import/commit': typeof ApiExpenseHistoryImportCommitRoute
  '/api/expense-history/import/preview': typeof ApiExpenseHistoryImportPreviewRoute
  '/api/expense-history/months/$month': typeof ApiExpenseHistoryMonthsMonthRoute
  '/api/expense-history/transactions/$id': typeof ApiExpenseHistoryTransactionsIdRouteWithChildren
  '/api/expense-history/transactions/batch': typeof ApiExpenseHistoryTransactionsBatchRoute
  '/_resource/clients/edit/$id/modal': typeof ResourceClientsEditIdModalRoute
  '/_resource/expenses/edit/$id/modal': typeof ResourceExpensesEditIdModalRoute
  '/_resource/expenses/history/create-expense/$id': typeof ResourceExpensesHistoryCreateExpenseIdRouteWithChildren
  '/_resource/expenses/history/edit/$id': typeof ResourceExpensesHistoryEditIdRouteWithChildren
  '/_resource/projects/edit/$id/modal': typeof ResourceProjectsEditIdModalRoute
  '/api/expense-history/transactions/$id/expense': typeof ApiExpenseHistoryTransactionsIdExpenseRoute
  '/_resource/expenses/history/create-expense/$id/modal': typeof ResourceExpensesHistoryCreateExpenseIdModalRoute
  '/_resource/expenses/history/edit/$id/modal': typeof ResourceExpensesHistoryEditIdModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pdf'
    | '/clients'
    | '/expenses'
    | '/invoices'
    | '/projects'
    | '/api/clients'
    | '/api/exchange-rates'
    | '/api/expenses'
    | '/api/invoices'
    | '/api/pdf'
    | '/api/projects'
    | '/api/settings'
    | '/clients/create'
    | '/expenses/create'
    | '/expenses/history'
    | '/invoices/$id'
    | '/invoices/create'
    | '/projects/create'
    | '/api/auth/$'
    | '/api/clients/$id'
    | '/api/expense-history/months'
    | '/api/expense-history/overview'
    | '/api/expenses/$id'
    | '/api/invoices/$id'
    | '/api/projects/$id'
    | '/clients/'
    | '/expenses/'
    | '/invoices/'
    | '/projects/'
    | '/clients/create/modal'
    | '/clients/edit/$id'
    | '/expenses/create/modal'
    | '/expenses/edit/$id'
    | '/projects/create/modal'
    | '/projects/edit/$id'
    | '/api/expense-history/import/commit'
    | '/api/expense-history/import/preview'
    | '/api/expense-history/months/$month'
    | '/api/expense-history/transactions/$id'
    | '/api/expense-history/transactions/batch'
    | '/clients/edit/$id/modal'
    | '/expenses/edit/$id/modal'
    | '/expenses/history/create-expense/$id'
    | '/expenses/history/edit/$id'
    | '/projects/edit/$id/modal'
    | '/api/expense-history/transactions/$id/expense'
    | '/expenses/history/create-expense/$id/modal'
    | '/expenses/history/edit/$id/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pdf'
    | '/api/clients'
    | '/api/exchange-rates'
    | '/api/expenses'
    | '/api/invoices'
    | '/api/pdf'
    | '/api/projects'
    | '/api/settings'
    | '/clients/create'
    | '/expenses/create'
    | '/expenses/history'
    | '/invoices/$id'
    | '/invoices/create'
    | '/projects/create'
    | '/api/auth/$'
    | '/api/clients/$id'
    | '/api/expense-history/months'
    | '/api/expense-history/overview'
    | '/api/expenses/$id'
    | '/api/invoices/$id'
    | '/api/projects/$id'
    | '/clients'
    | '/expenses'
    | '/invoices'
    | '/projects'
    | '/clients/create/modal'
    | '/clients/edit/$id'
    | '/expenses/create/modal'
    | '/expenses/edit/$id'
    | '/projects/create/modal'
    | '/projects/edit/$id'
    | '/api/expense-history/import/commit'
    | '/api/expense-history/import/preview'
    | '/api/expense-history/months/$month'
    | '/api/expense-history/transactions/$id'
    | '/api/expense-history/transactions/batch'
    | '/clients/edit/$id/modal'
    | '/expenses/edit/$id/modal'
    | '/expenses/history/create-expense/$id'
    | '/expenses/history/edit/$id'
    | '/projects/edit/$id/modal'
    | '/api/expense-history/transactions/$id/expense'
    | '/expenses/history/create-expense/$id/modal'
    | '/expenses/history/edit/$id/modal'
  id:
    | '__root__'
    | '/'
    | '/_resource'
    | '/login'
    | '/pdf'
    | '/_resource/clients'
    | '/_resource/expenses'
    | '/_resource/invoices'
    | '/_resource/projects'
    | '/api/clients'
    | '/api/exchange-rates'
    | '/api/expenses'
    | '/api/invoices'
    | '/api/pdf'
    | '/api/projects'
    | '/api/settings'
    | '/_resource/clients/create'
    | '/_resource/expenses/create'
    | '/_resource/expenses/history'
    | '/_resource/invoices/$id'
    | '/_resource/invoices/create'
    | '/_resource/projects/create'
    | '/api/auth/$'
    | '/api/clients/$id'
    | '/api/expense-history/months'
    | '/api/expense-history/overview'
    | '/api/expenses/$id'
    | '/api/invoices/$id'
    | '/api/projects/$id'
    | '/_resource/clients/'
    | '/_resource/expenses/'
    | '/_resource/invoices/'
    | '/_resource/projects/'
    | '/_resource/clients/create/modal'
    | '/_resource/clients/edit/$id'
    | '/_resource/expenses/create/modal'
    | '/_resource/expenses/edit/$id'
    | '/_resource/projects/create/modal'
    | '/_resource/projects/edit/$id'
    | '/api/expense-history/import/commit'
    | '/api/expense-history/import/preview'
    | '/api/expense-history/months/$month'
    | '/api/expense-history/transactions/$id'
    | '/api/expense-history/transactions/batch'
    | '/_resource/clients/edit/$id/modal'
    | '/_resource/expenses/edit/$id/modal'
    | '/_resource/expenses/history/create-expense/$id'
    | '/_resource/expenses/history/edit/$id'
    | '/_resource/projects/edit/$id/modal'
    | '/api/expense-history/transactions/$id/expense'
    | '/_resource/expenses/history/create-expense/$id/modal'
    | '/_resource/expenses/history/edit/$id/modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResourceRoute: typeof ResourceRouteWithChildren
  LoginRoute: typeof LoginRoute
  PdfRoute: typeof PdfRoute
  ApiClientsRoute: typeof ApiClientsRouteWithChildren
  ApiExchangeRatesRoute: typeof ApiExchangeRatesRoute
  ApiExpensesRoute: typeof ApiExpensesRouteWithChildren
  ApiInvoicesRoute: typeof ApiInvoicesRouteWithChildren
  ApiPdfRoute: typeof ApiPdfRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiExpenseHistoryMonthsRoute: typeof ApiExpenseHistoryMonthsRouteWithChildren
  ApiExpenseHistoryOverviewRoute: typeof ApiExpenseHistoryOverviewRoute
  ApiExpenseHistoryImportCommitRoute: typeof ApiExpenseHistoryImportCommitRoute
  ApiExpenseHistoryImportPreviewRoute: typeof ApiExpenseHistoryImportPreviewRoute
  ApiExpenseHistoryTransactionsIdRoute: typeof ApiExpenseHistoryTransactionsIdRouteWithChildren
  ApiExpenseHistoryTransactionsBatchRoute: typeof ApiExpenseHistoryTransactionsBatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resource': {
      id: '/_resource'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses': {
      id: '/api/expenses'
      path: '/api/expenses'
      fullPath: '/api/expenses'
      preLoaderRoute: typeof ApiExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rates': {
      id: '/api/exchange-rates'
      path: '/api/exchange-rates'
      fullPath: '/api/exchange-rates'
      preLoaderRoute: typeof ApiExchangeRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resource/projects': {
      id: '/_resource/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ResourceProjectsRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/_resource/invoices': {
      id: '/_resource/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof ResourceInvoicesRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/_resource/expenses': {
      id: '/_resource/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ResourceExpensesRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/_resource/clients': {
      id: '/_resource/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ResourceClientsRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/_resource/projects/': {
      id: '/_resource/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ResourceProjectsIndexRouteImport
      parentRoute: typeof ResourceProjectsRoute
    }
    '/_resource/invoices/': {
      id: '/_resource/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof ResourceInvoicesIndexRouteImport
      parentRoute: typeof ResourceInvoicesRoute
    }
    '/_resource/expenses/': {
      id: '/_resource/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ResourceExpensesIndexRouteImport
      parentRoute: typeof ResourceExpensesRoute
    }
    '/_resource/clients/': {
      id: '/_resource/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ResourceClientsIndexRouteImport
      parentRoute: typeof ResourceClientsRoute
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/invoices/$id': {
      id: '/api/invoices/$id'
      path: '/$id'
      fullPath: '/api/invoices/$id'
      preLoaderRoute: typeof ApiInvoicesIdRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/expenses/$id': {
      id: '/api/expenses/$id'
      path: '/$id'
      fullPath: '/api/expenses/$id'
      preLoaderRoute: typeof ApiExpensesIdRouteImport
      parentRoute: typeof ApiExpensesRoute
    }
    '/api/expense-history/overview': {
      id: '/api/expense-history/overview'
      path: '/api/expense-history/overview'
      fullPath: '/api/expense-history/overview'
      preLoaderRoute: typeof ApiExpenseHistoryOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expense-history/months': {
      id: '/api/expense-history/months'
      path: '/api/expense-history/months'
      fullPath: '/api/expense-history/months'
      preLoaderRoute: typeof ApiExpenseHistoryMonthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$id': {
      id: '/api/clients/$id'
      path: '/$id'
      fullPath: '/api/clients/$id'
      preLoaderRoute: typeof ApiClientsIdRouteImport
      parentRoute: typeof ApiClientsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resource/projects/create': {
      id: '/_resource/projects/create'
      path: '/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ResourceProjectsCreateRouteImport
      parentRoute: typeof ResourceProjectsRoute
    }
    '/_resource/invoices/create': {
      id: '/_resource/invoices/create'
      path: '/create'
      fullPath: '/invoices/create'
      preLoaderRoute: typeof ResourceInvoicesCreateRouteImport
      parentRoute: typeof ResourceInvoicesRoute
    }
    '/_resource/invoices/$id': {
      id: '/_resource/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof ResourceInvoicesIdRouteImport
      parentRoute: typeof ResourceInvoicesRoute
    }
    '/_resource/expenses/history': {
      id: '/_resource/expenses/history'
      path: '/history'
      fullPath: '/expenses/history'
      preLoaderRoute: typeof ResourceExpensesHistoryRouteImport
      parentRoute: typeof ResourceExpensesRoute
    }
    '/_resource/expenses/create': {
      id: '/_resource/expenses/create'
      path: '/create'
      fullPath: '/expenses/create'
      preLoaderRoute: typeof ResourceExpensesCreateRouteImport
      parentRoute: typeof ResourceExpensesRoute
    }
    '/_resource/clients/create': {
      id: '/_resource/clients/create'
      path: '/create'
      fullPath: '/clients/create'
      preLoaderRoute: typeof ResourceClientsCreateRouteImport
      parentRoute: typeof ResourceClientsRoute
    }
    '/api/expense-history/transactions/batch': {
      id: '/api/expense-history/transactions/batch'
      path: '/api/expense-history/transactions/batch'
      fullPath: '/api/expense-history/transactions/batch'
      preLoaderRoute: typeof ApiExpenseHistoryTransactionsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expense-history/transactions/$id': {
      id: '/api/expense-history/transactions/$id'
      path: '/api/expense-history/transactions/$id'
      fullPath: '/api/expense-history/transactions/$id'
      preLoaderRoute: typeof ApiExpenseHistoryTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expense-history/months/$month': {
      id: '/api/expense-history/months/$month'
      path: '/$month'
      fullPath: '/api/expense-history/months/$month'
      preLoaderRoute: typeof ApiExpenseHistoryMonthsMonthRouteImport
      parentRoute: typeof ApiExpenseHistoryMonthsRoute
    }
    '/api/expense-history/import/preview': {
      id: '/api/expense-history/import/preview'
      path: '/api/expense-history/import/preview'
      fullPath: '/api/expense-history/import/preview'
      preLoaderRoute: typeof ApiExpenseHistoryImportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expense-history/import/commit': {
      id: '/api/expense-history/import/commit'
      path: '/api/expense-history/import/commit'
      fullPath: '/api/expense-history/import/commit'
      preLoaderRoute: typeof ApiExpenseHistoryImportCommitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resource/projects/edit/$id': {
      id: '/_resource/projects/edit/$id'
      path: '/edit/$id'
      fullPath: '/projects/edit/$id'
      preLoaderRoute: typeof ResourceProjectsEditIdRouteImport
      parentRoute: typeof ResourceProjectsRoute
    }
    '/_resource/projects/create/modal': {
      id: '/_resource/projects/create/modal'
      path: '/modal'
      fullPath: '/projects/create/modal'
      preLoaderRoute: typeof ResourceProjectsCreateModalRouteImport
      parentRoute: typeof ResourceProjectsCreateRoute
    }
    '/_resource/expenses/edit/$id': {
      id: '/_resource/expenses/edit/$id'
      path: '/edit/$id'
      fullPath: '/expenses/edit/$id'
      preLoaderRoute: typeof ResourceExpensesEditIdRouteImport
      parentRoute: typeof ResourceExpensesRoute
    }
    '/_resource/expenses/create/modal': {
      id: '/_resource/expenses/create/modal'
      path: '/modal'
      fullPath: '/expenses/create/modal'
      preLoaderRoute: typeof ResourceExpensesCreateModalRouteImport
      parentRoute: typeof ResourceExpensesCreateRoute
    }
    '/_resource/clients/edit/$id': {
      id: '/_resource/clients/edit/$id'
      path: '/edit/$id'
      fullPath: '/clients/edit/$id'
      preLoaderRoute: typeof ResourceClientsEditIdRouteImport
      parentRoute: typeof ResourceClientsRoute
    }
    '/_resource/clients/create/modal': {
      id: '/_resource/clients/create/modal'
      path: '/modal'
      fullPath: '/clients/create/modal'
      preLoaderRoute: typeof ResourceClientsCreateModalRouteImport
      parentRoute: typeof ResourceClientsCreateRoute
    }
    '/api/expense-history/transactions/$id/expense': {
      id: '/api/expense-history/transactions/$id/expense'
      path: '/expense'
      fullPath: '/api/expense-history/transactions/$id/expense'
      preLoaderRoute: typeof ApiExpenseHistoryTransactionsIdExpenseRouteImport
      parentRoute: typeof ApiExpenseHistoryTransactionsIdRoute
    }
    '/_resource/projects/edit/$id/modal': {
      id: '/_resource/projects/edit/$id/modal'
      path: '/modal'
      fullPath: '/projects/edit/$id/modal'
      preLoaderRoute: typeof ResourceProjectsEditIdModalRouteImport
      parentRoute: typeof ResourceProjectsEditIdRoute
    }
    '/_resource/expenses/history/edit/$id': {
      id: '/_resource/expenses/history/edit/$id'
      path: '/edit/$id'
      fullPath: '/expenses/history/edit/$id'
      preLoaderRoute: typeof ResourceExpensesHistoryEditIdRouteImport
      parentRoute: typeof ResourceExpensesHistoryRoute
    }
    '/_resource/expenses/history/create-expense/$id': {
      id: '/_resource/expenses/history/create-expense/$id'
      path: '/create-expense/$id'
      fullPath: '/expenses/history/create-expense/$id'
      preLoaderRoute: typeof ResourceExpensesHistoryCreateExpenseIdRouteImport
      parentRoute: typeof ResourceExpensesHistoryRoute
    }
    '/_resource/expenses/edit/$id/modal': {
      id: '/_resource/expenses/edit/$id/modal'
      path: '/modal'
      fullPath: '/expenses/edit/$id/modal'
      preLoaderRoute: typeof ResourceExpensesEditIdModalRouteImport
      parentRoute: typeof ResourceExpensesEditIdRoute
    }
    '/_resource/clients/edit/$id/modal': {
      id: '/_resource/clients/edit/$id/modal'
      path: '/modal'
      fullPath: '/clients/edit/$id/modal'
      preLoaderRoute: typeof ResourceClientsEditIdModalRouteImport
      parentRoute: typeof ResourceClientsEditIdRoute
    }
    '/_resource/expenses/history/edit/$id/modal': {
      id: '/_resource/expenses/history/edit/$id/modal'
      path: '/modal'
      fullPath: '/expenses/history/edit/$id/modal'
      preLoaderRoute: typeof ResourceExpensesHistoryEditIdModalRouteImport
      parentRoute: typeof ResourceExpensesHistoryEditIdRoute
    }
    '/_resource/expenses/history/create-expense/$id/modal': {
      id: '/_resource/expenses/history/create-expense/$id/modal'
      path: '/modal'
      fullPath: '/expenses/history/create-expense/$id/modal'
      preLoaderRoute: typeof ResourceExpensesHistoryCreateExpenseIdModalRouteImport
      parentRoute: typeof ResourceExpensesHistoryCreateExpenseIdRoute
    }
  }
}

interface ResourceClientsCreateRouteChildren {
  ResourceClientsCreateModalRoute: typeof ResourceClientsCreateModalRoute
}

const ResourceClientsCreateRouteChildren: ResourceClientsCreateRouteChildren = {
  ResourceClientsCreateModalRoute: ResourceClientsCreateModalRoute,
}

const ResourceClientsCreateRouteWithChildren =
  ResourceClientsCreateRoute._addFileChildren(
    ResourceClientsCreateRouteChildren,
  )

interface ResourceClientsEditIdRouteChildren {
  ResourceClientsEditIdModalRoute: typeof ResourceClientsEditIdModalRoute
}

const ResourceClientsEditIdRouteChildren: ResourceClientsEditIdRouteChildren = {
  ResourceClientsEditIdModalRoute: ResourceClientsEditIdModalRoute,
}

const ResourceClientsEditIdRouteWithChildren =
  ResourceClientsEditIdRoute._addFileChildren(
    ResourceClientsEditIdRouteChildren,
  )

interface ResourceClientsRouteChildren {
  ResourceClientsCreateRoute: typeof ResourceClientsCreateRouteWithChildren
  ResourceClientsIndexRoute: typeof ResourceClientsIndexRoute
  ResourceClientsEditIdRoute: typeof ResourceClientsEditIdRouteWithChildren
}

const ResourceClientsRouteChildren: ResourceClientsRouteChildren = {
  ResourceClientsCreateRoute: ResourceClientsCreateRouteWithChildren,
  ResourceClientsIndexRoute: ResourceClientsIndexRoute,
  ResourceClientsEditIdRoute: ResourceClientsEditIdRouteWithChildren,
}

const ResourceClientsRouteWithChildren = ResourceClientsRoute._addFileChildren(
  ResourceClientsRouteChildren,
)

interface ResourceExpensesCreateRouteChildren {
  ResourceExpensesCreateModalRoute: typeof ResourceExpensesCreateModalRoute
}

const ResourceExpensesCreateRouteChildren: ResourceExpensesCreateRouteChildren =
  {
    ResourceExpensesCreateModalRoute: ResourceExpensesCreateModalRoute,
  }

const ResourceExpensesCreateRouteWithChildren =
  ResourceExpensesCreateRoute._addFileChildren(
    ResourceExpensesCreateRouteChildren,
  )

interface ResourceExpensesHistoryCreateExpenseIdRouteChildren {
  ResourceExpensesHistoryCreateExpenseIdModalRoute: typeof ResourceExpensesHistoryCreateExpenseIdModalRoute
}

const ResourceExpensesHistoryCreateExpenseIdRouteChildren: ResourceExpensesHistoryCreateExpenseIdRouteChildren =
  {
    ResourceExpensesHistoryCreateExpenseIdModalRoute:
      ResourceExpensesHistoryCreateExpenseIdModalRoute,
  }

const ResourceExpensesHistoryCreateExpenseIdRouteWithChildren =
  ResourceExpensesHistoryCreateExpenseIdRoute._addFileChildren(
    ResourceExpensesHistoryCreateExpenseIdRouteChildren,
  )

interface ResourceExpensesHistoryEditIdRouteChildren {
  ResourceExpensesHistoryEditIdModalRoute: typeof ResourceExpensesHistoryEditIdModalRoute
}

const ResourceExpensesHistoryEditIdRouteChildren: ResourceExpensesHistoryEditIdRouteChildren =
  {
    ResourceExpensesHistoryEditIdModalRoute:
      ResourceExpensesHistoryEditIdModalRoute,
  }

const ResourceExpensesHistoryEditIdRouteWithChildren =
  ResourceExpensesHistoryEditIdRoute._addFileChildren(
    ResourceExpensesHistoryEditIdRouteChildren,
  )

interface ResourceExpensesHistoryRouteChildren {
  ResourceExpensesHistoryCreateExpenseIdRoute: typeof ResourceExpensesHistoryCreateExpenseIdRouteWithChildren
  ResourceExpensesHistoryEditIdRoute: typeof ResourceExpensesHistoryEditIdRouteWithChildren
}

const ResourceExpensesHistoryRouteChildren: ResourceExpensesHistoryRouteChildren =
  {
    ResourceExpensesHistoryCreateExpenseIdRoute:
      ResourceExpensesHistoryCreateExpenseIdRouteWithChildren,
    ResourceExpensesHistoryEditIdRoute:
      ResourceExpensesHistoryEditIdRouteWithChildren,
  }

const ResourceExpensesHistoryRouteWithChildren =
  ResourceExpensesHistoryRoute._addFileChildren(
    ResourceExpensesHistoryRouteChildren,
  )

interface ResourceExpensesEditIdRouteChildren {
  ResourceExpensesEditIdModalRoute: typeof ResourceExpensesEditIdModalRoute
}

const ResourceExpensesEditIdRouteChildren: ResourceExpensesEditIdRouteChildren =
  {
    ResourceExpensesEditIdModalRoute: ResourceExpensesEditIdModalRoute,
  }

const ResourceExpensesEditIdRouteWithChildren =
  ResourceExpensesEditIdRoute._addFileChildren(
    ResourceExpensesEditIdRouteChildren,
  )

interface ResourceExpensesRouteChildren {
  ResourceExpensesCreateRoute: typeof ResourceExpensesCreateRouteWithChildren
  ResourceExpensesHistoryRoute: typeof ResourceExpensesHistoryRouteWithChildren
  ResourceExpensesIndexRoute: typeof ResourceExpensesIndexRoute
  ResourceExpensesEditIdRoute: typeof ResourceExpensesEditIdRouteWithChildren
}

const ResourceExpensesRouteChildren: ResourceExpensesRouteChildren = {
  ResourceExpensesCreateRoute: ResourceExpensesCreateRouteWithChildren,
  ResourceExpensesHistoryRoute: ResourceExpensesHistoryRouteWithChildren,
  ResourceExpensesIndexRoute: ResourceExpensesIndexRoute,
  ResourceExpensesEditIdRoute: ResourceExpensesEditIdRouteWithChildren,
}

const ResourceExpensesRouteWithChildren =
  ResourceExpensesRoute._addFileChildren(ResourceExpensesRouteChildren)

interface ResourceInvoicesRouteChildren {
  ResourceInvoicesIdRoute: typeof ResourceInvoicesIdRoute
  ResourceInvoicesCreateRoute: typeof ResourceInvoicesCreateRoute
  ResourceInvoicesIndexRoute: typeof ResourceInvoicesIndexRoute
}

const ResourceInvoicesRouteChildren: ResourceInvoicesRouteChildren = {
  ResourceInvoicesIdRoute: ResourceInvoicesIdRoute,
  ResourceInvoicesCreateRoute: ResourceInvoicesCreateRoute,
  ResourceInvoicesIndexRoute: ResourceInvoicesIndexRoute,
}

const ResourceInvoicesRouteWithChildren =
  ResourceInvoicesRoute._addFileChildren(ResourceInvoicesRouteChildren)

interface ResourceProjectsCreateRouteChildren {
  ResourceProjectsCreateModalRoute: typeof ResourceProjectsCreateModalRoute
}

const ResourceProjectsCreateRouteChildren: ResourceProjectsCreateRouteChildren =
  {
    ResourceProjectsCreateModalRoute: ResourceProjectsCreateModalRoute,
  }

const ResourceProjectsCreateRouteWithChildren =
  ResourceProjectsCreateRoute._addFileChildren(
    ResourceProjectsCreateRouteChildren,
  )

interface ResourceProjectsEditIdRouteChildren {
  ResourceProjectsEditIdModalRoute: typeof ResourceProjectsEditIdModalRoute
}

const ResourceProjectsEditIdRouteChildren: ResourceProjectsEditIdRouteChildren =
  {
    ResourceProjectsEditIdModalRoute: ResourceProjectsEditIdModalRoute,
  }

const ResourceProjectsEditIdRouteWithChildren =
  ResourceProjectsEditIdRoute._addFileChildren(
    ResourceProjectsEditIdRouteChildren,
  )

interface ResourceProjectsRouteChildren {
  ResourceProjectsCreateRoute: typeof ResourceProjectsCreateRouteWithChildren
  ResourceProjectsIndexRoute: typeof ResourceProjectsIndexRoute
  ResourceProjectsEditIdRoute: typeof ResourceProjectsEditIdRouteWithChildren
}

const ResourceProjectsRouteChildren: ResourceProjectsRouteChildren = {
  ResourceProjectsCreateRoute: ResourceProjectsCreateRouteWithChildren,
  ResourceProjectsIndexRoute: ResourceProjectsIndexRoute,
  ResourceProjectsEditIdRoute: ResourceProjectsEditIdRouteWithChildren,
}

const ResourceProjectsRouteWithChildren =
  ResourceProjectsRoute._addFileChildren(ResourceProjectsRouteChildren)

interface ResourceRouteChildren {
  ResourceClientsRoute: typeof ResourceClientsRouteWithChildren
  ResourceExpensesRoute: typeof ResourceExpensesRouteWithChildren
  ResourceInvoicesRoute: typeof ResourceInvoicesRouteWithChildren
  ResourceProjectsRoute: typeof ResourceProjectsRouteWithChildren
}

const ResourceRouteChildren: ResourceRouteChildren = {
  ResourceClientsRoute: ResourceClientsRouteWithChildren,
  ResourceExpensesRoute: ResourceExpensesRouteWithChildren,
  ResourceInvoicesRoute: ResourceInvoicesRouteWithChildren,
  ResourceProjectsRoute: ResourceProjectsRouteWithChildren,
}

const ResourceRouteWithChildren = ResourceRoute._addFileChildren(
  ResourceRouteChildren,
)

interface ApiClientsRouteChildren {
  ApiClientsIdRoute: typeof ApiClientsIdRoute
}

const ApiClientsRouteChildren: ApiClientsRouteChildren = {
  ApiClientsIdRoute: ApiClientsIdRoute,
}

const ApiClientsRouteWithChildren = ApiClientsRoute._addFileChildren(
  ApiClientsRouteChildren,
)

interface ApiExpensesRouteChildren {
  ApiExpensesIdRoute: typeof ApiExpensesIdRoute
}

const ApiExpensesRouteChildren: ApiExpensesRouteChildren = {
  ApiExpensesIdRoute: ApiExpensesIdRoute,
}

const ApiExpensesRouteWithChildren = ApiExpensesRoute._addFileChildren(
  ApiExpensesRouteChildren,
)

interface ApiInvoicesRouteChildren {
  ApiInvoicesIdRoute: typeof ApiInvoicesIdRoute
}

const ApiInvoicesRouteChildren: ApiInvoicesRouteChildren = {
  ApiInvoicesIdRoute: ApiInvoicesIdRoute,
}

const ApiInvoicesRouteWithChildren = ApiInvoicesRoute._addFileChildren(
  ApiInvoicesRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

interface ApiExpenseHistoryMonthsRouteChildren {
  ApiExpenseHistoryMonthsMonthRoute: typeof ApiExpenseHistoryMonthsMonthRoute
}

const ApiExpenseHistoryMonthsRouteChildren: ApiExpenseHistoryMonthsRouteChildren =
  {
    ApiExpenseHistoryMonthsMonthRoute: ApiExpenseHistoryMonthsMonthRoute,
  }

const ApiExpenseHistoryMonthsRouteWithChildren =
  ApiExpenseHistoryMonthsRoute._addFileChildren(
    ApiExpenseHistoryMonthsRouteChildren,
  )

interface ApiExpenseHistoryTransactionsIdRouteChildren {
  ApiExpenseHistoryTransactionsIdExpenseRoute: typeof ApiExpenseHistoryTransactionsIdExpenseRoute
}

const ApiExpenseHistoryTransactionsIdRouteChildren: ApiExpenseHistoryTransactionsIdRouteChildren =
  {
    ApiExpenseHistoryTransactionsIdExpenseRoute:
      ApiExpenseHistoryTransactionsIdExpenseRoute,
  }

const ApiExpenseHistoryTransactionsIdRouteWithChildren =
  ApiExpenseHistoryTransactionsIdRoute._addFileChildren(
    ApiExpenseHistoryTransactionsIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResourceRoute: ResourceRouteWithChildren,
  LoginRoute: LoginRoute,
  PdfRoute: PdfRoute,
  ApiClientsRoute: ApiClientsRouteWithChildren,
  ApiExchangeRatesRoute: ApiExchangeRatesRoute,
  ApiExpensesRoute: ApiExpensesRouteWithChildren,
  ApiInvoicesRoute: ApiInvoicesRouteWithChildren,
  ApiPdfRoute: ApiPdfRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiExpenseHistoryMonthsRoute: ApiExpenseHistoryMonthsRouteWithChildren,
  ApiExpenseHistoryOverviewRoute: ApiExpenseHistoryOverviewRoute,
  ApiExpenseHistoryImportCommitRoute: ApiExpenseHistoryImportCommitRoute,
  ApiExpenseHistoryImportPreviewRoute: ApiExpenseHistoryImportPreviewRoute,
  ApiExpenseHistoryTransactionsIdRoute:
    ApiExpenseHistoryTransactionsIdRouteWithChildren,
  ApiExpenseHistoryTransactionsBatchRoute:
    ApiExpenseHistoryTransactionsBatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
