/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResourceRouteImport } from './routes/_resource'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiPdfRouteImport } from './routes/api/pdf'
import { Route as ApiExpensesRouteImport } from './routes/api/expenses'
import { Route as ApiExchangeRatesRouteImport } from './routes/api/exchange-rates'
import { Route as ApiClientsRouteImport } from './routes/api/clients'
import { Route as ResourceProjectsRouteImport } from './routes/_resource/projects'
import { Route as ResourceExpensesRouteImport } from './routes/_resource/expenses'
import { Route as ResourceClientsRouteImport } from './routes/_resource/clients'
import { Route as ResourceProjectsIndexRouteImport } from './routes/_resource/projects/index'
import { Route as ResourceExpensesIndexRouteImport } from './routes/_resource/expenses/index'
import { Route as ResourceClientsIndexRouteImport } from './routes/_resource/clients/index'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiExpensesIdRouteImport } from './routes/api/expenses/$id'
import { Route as ApiClientsIdRouteImport } from './routes/api/clients/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ResourceProjectsCreateRouteImport } from './routes/_resource/projects/create'
import { Route as ResourceExpensesCreateRouteImport } from './routes/_resource/expenses/create'
import { Route as ResourceClientsCreateRouteImport } from './routes/_resource/clients/create'
import { Route as ResourceProjectsEditIdRouteImport } from './routes/_resource/projects/edit/$id'
import { Route as ResourceProjectsCreateModalRouteImport } from './routes/_resource/projects/create.modal'
import { Route as ResourceExpensesEditIdRouteImport } from './routes/_resource/expenses/edit/$id'
import { Route as ResourceExpensesCreateModalRouteImport } from './routes/_resource/expenses/create.modal'
import { Route as ResourceClientsEditIdRouteImport } from './routes/_resource/clients/edit/$id'
import { Route as ResourceClientsCreateModalRouteImport } from './routes/_resource/clients/create.modal'
import { Route as ResourceProjectsEditIdModalRouteImport } from './routes/_resource/projects/edit.$id.modal'
import { Route as ResourceExpensesEditIdModalRouteImport } from './routes/_resource/expenses/edit.$id.modal'
import { Route as ResourceClientsEditIdModalRouteImport } from './routes/_resource/clients/edit.$id.modal'

const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceRoute = ResourceRouteImport.update({
  id: '/_resource',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesRoute = ApiExpensesRouteImport.update({
  id: '/api/expenses',
  path: '/api/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRatesRoute = ApiExchangeRatesRouteImport.update({
  id: '/api/exchange-rates',
  path: '/api/exchange-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceProjectsRoute = ResourceProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ResourceRoute,
} as any)
const ResourceExpensesRoute = ResourceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ResourceRoute,
} as any)
const ResourceClientsRoute = ResourceClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ResourceRoute,
} as any)
const ResourceProjectsIndexRoute = ResourceProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourceProjectsRoute,
} as any)
const ResourceExpensesIndexRoute = ResourceExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourceExpensesRoute,
} as any)
const ResourceClientsIndexRoute = ResourceClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourceClientsRoute,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiExpensesIdRoute = ApiExpensesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExpensesRoute,
} as any)
const ApiClientsIdRoute = ApiClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceProjectsCreateRoute = ResourceProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ResourceProjectsRoute,
} as any)
const ResourceExpensesCreateRoute = ResourceExpensesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ResourceExpensesRoute,
} as any)
const ResourceClientsCreateRoute = ResourceClientsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ResourceClientsRoute,
} as any)
const ResourceProjectsEditIdRoute = ResourceProjectsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ResourceProjectsRoute,
} as any)
const ResourceProjectsCreateModalRoute =
  ResourceProjectsCreateModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceProjectsCreateRoute,
  } as any)
const ResourceExpensesEditIdRoute = ResourceExpensesEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ResourceExpensesRoute,
} as any)
const ResourceExpensesCreateModalRoute =
  ResourceExpensesCreateModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceExpensesCreateRoute,
  } as any)
const ResourceClientsEditIdRoute = ResourceClientsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ResourceClientsRoute,
} as any)
const ResourceClientsCreateModalRoute =
  ResourceClientsCreateModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceClientsCreateRoute,
  } as any)
const ResourceProjectsEditIdModalRoute =
  ResourceProjectsEditIdModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceProjectsEditIdRoute,
  } as any)
const ResourceExpensesEditIdModalRoute =
  ResourceExpensesEditIdModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceExpensesEditIdRoute,
  } as any)
const ResourceClientsEditIdModalRoute =
  ResourceClientsEditIdModalRouteImport.update({
    id: '/modal',
    path: '/modal',
    getParentRoute: () => ResourceClientsEditIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pdf': typeof PdfRoute
  '/clients': typeof ResourceClientsRouteWithChildren
  '/expenses': typeof ResourceExpensesRouteWithChildren
  '/projects': typeof ResourceProjectsRouteWithChildren
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/clients/create': typeof ResourceClientsCreateRouteWithChildren
  '/expenses/create': typeof ResourceExpensesCreateRouteWithChildren
  '/projects/create': typeof ResourceProjectsCreateRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/clients/': typeof ResourceClientsIndexRoute
  '/expenses/': typeof ResourceExpensesIndexRoute
  '/projects/': typeof ResourceProjectsIndexRoute
  '/clients/create/modal': typeof ResourceClientsCreateModalRoute
  '/clients/edit/$id': typeof ResourceClientsEditIdRouteWithChildren
  '/expenses/create/modal': typeof ResourceExpensesCreateModalRoute
  '/expenses/edit/$id': typeof ResourceExpensesEditIdRouteWithChildren
  '/projects/create/modal': typeof ResourceProjectsCreateModalRoute
  '/projects/edit/$id': typeof ResourceProjectsEditIdRouteWithChildren
  '/clients/edit/$id/modal': typeof ResourceClientsEditIdModalRoute
  '/expenses/edit/$id/modal': typeof ResourceExpensesEditIdModalRoute
  '/projects/edit/$id/modal': typeof ResourceProjectsEditIdModalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pdf': typeof PdfRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/clients/create': typeof ResourceClientsCreateRouteWithChildren
  '/expenses/create': typeof ResourceExpensesCreateRouteWithChildren
  '/projects/create': typeof ResourceProjectsCreateRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/clients': typeof ResourceClientsIndexRoute
  '/expenses': typeof ResourceExpensesIndexRoute
  '/projects': typeof ResourceProjectsIndexRoute
  '/clients/create/modal': typeof ResourceClientsCreateModalRoute
  '/clients/edit/$id': typeof ResourceClientsEditIdRouteWithChildren
  '/expenses/create/modal': typeof ResourceExpensesCreateModalRoute
  '/expenses/edit/$id': typeof ResourceExpensesEditIdRouteWithChildren
  '/projects/create/modal': typeof ResourceProjectsCreateModalRoute
  '/projects/edit/$id': typeof ResourceProjectsEditIdRouteWithChildren
  '/clients/edit/$id/modal': typeof ResourceClientsEditIdModalRoute
  '/expenses/edit/$id/modal': typeof ResourceExpensesEditIdModalRoute
  '/projects/edit/$id/modal': typeof ResourceProjectsEditIdModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_resource': typeof ResourceRouteWithChildren
  '/login': typeof LoginRoute
  '/pdf': typeof PdfRoute
  '/_resource/clients': typeof ResourceClientsRouteWithChildren
  '/_resource/expenses': typeof ResourceExpensesRouteWithChildren
  '/_resource/projects': typeof ResourceProjectsRouteWithChildren
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/_resource/clients/create': typeof ResourceClientsCreateRouteWithChildren
  '/_resource/expenses/create': typeof ResourceExpensesCreateRouteWithChildren
  '/_resource/projects/create': typeof ResourceProjectsCreateRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/_resource/clients/': typeof ResourceClientsIndexRoute
  '/_resource/expenses/': typeof ResourceExpensesIndexRoute
  '/_resource/projects/': typeof ResourceProjectsIndexRoute
  '/_resource/clients/create/modal': typeof ResourceClientsCreateModalRoute
  '/_resource/clients/edit/$id': typeof ResourceClientsEditIdRouteWithChildren
  '/_resource/expenses/create/modal': typeof ResourceExpensesCreateModalRoute
  '/_resource/expenses/edit/$id': typeof ResourceExpensesEditIdRouteWithChildren
  '/_resource/projects/create/modal': typeof ResourceProjectsCreateModalRoute
  '/_resource/projects/edit/$id': typeof ResourceProjectsEditIdRouteWithChildren
  '/_resource/clients/edit/$id/modal': typeof ResourceClientsEditIdModalRoute
  '/_resource/expenses/edit/$id/modal': typeof ResourceExpensesEditIdModalRoute
  '/_resource/projects/edit/$id/modal': typeof ResourceProjectsEditIdModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pdf'
    | '/clients'
    | '/expenses'
    | '/projects'
    | '/api/clients'
    | '/api/exchange-rates'
    | '/api/expenses'
    | '/api/pdf'
    | '/api/projects'
    | '/api/settings'
    | '/clients/create'
    | '/expenses/create'
    | '/projects/create'
    | '/api/auth/$'
    | '/api/clients/$id'
    | '/api/expenses/$id'
    | '/api/projects/$id'
    | '/clients/'
    | '/expenses/'
    | '/projects/'
    | '/clients/create/modal'
    | '/clients/edit/$id'
    | '/expenses/create/modal'
    | '/expenses/edit/$id'
    | '/projects/create/modal'
    | '/projects/edit/$id'
    | '/clients/edit/$id/modal'
    | '/expenses/edit/$id/modal'
    | '/projects/edit/$id/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pdf'
    | '/api/clients'
    | '/api/exchange-rates'
    | '/api/expenses'
    | '/api/pdf'
    | '/api/projects'
    | '/api/settings'
    | '/clients/create'
    | '/expenses/create'
    | '/projects/create'
    | '/api/auth/$'
    | '/api/clients/$id'
    | '/api/expenses/$id'
    | '/api/projects/$id'
    | '/clients'
    | '/expenses'
    | '/projects'
    | '/clients/create/modal'
    | '/clients/edit/$id'
    | '/expenses/create/modal'
    | '/expenses/edit/$id'
    | '/projects/create/modal'
    | '/projects/edit/$id'
    | '/clients/edit/$id/modal'
    | '/expenses/edit/$id/modal'
    | '/projects/edit/$id/modal'
  id:
    | '__root__'
    | '/'
    | '/_resource'
    | '/login'
    | '/pdf'
    | '/_resource/clients'
    | '/_resource/expenses'
    | '/_resource/projects'
    | '/api/clients'
    | '/api/exchange-rates'
    | '/api/expenses'
    | '/api/pdf'
    | '/api/projects'
    | '/api/settings'
    | '/_resource/clients/create'
    | '/_resource/expenses/create'
    | '/_resource/projects/create'
    | '/api/auth/$'
    | '/api/clients/$id'
    | '/api/expenses/$id'
    | '/api/projects/$id'
    | '/_resource/clients/'
    | '/_resource/expenses/'
    | '/_resource/projects/'
    | '/_resource/clients/create/modal'
    | '/_resource/clients/edit/$id'
    | '/_resource/expenses/create/modal'
    | '/_resource/expenses/edit/$id'
    | '/_resource/projects/create/modal'
    | '/_resource/projects/edit/$id'
    | '/_resource/clients/edit/$id/modal'
    | '/_resource/expenses/edit/$id/modal'
    | '/_resource/projects/edit/$id/modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResourceRoute: typeof ResourceRouteWithChildren
  LoginRoute: typeof LoginRoute
  PdfRoute: typeof PdfRoute
  ApiClientsRoute: typeof ApiClientsRouteWithChildren
  ApiExchangeRatesRoute: typeof ApiExchangeRatesRoute
  ApiExpensesRoute: typeof ApiExpensesRouteWithChildren
  ApiPdfRoute: typeof ApiPdfRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resource': {
      id: '/_resource'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses': {
      id: '/api/expenses'
      path: '/api/expenses'
      fullPath: '/api/expenses'
      preLoaderRoute: typeof ApiExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rates': {
      id: '/api/exchange-rates'
      path: '/api/exchange-rates'
      fullPath: '/api/exchange-rates'
      preLoaderRoute: typeof ApiExchangeRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resource/projects': {
      id: '/_resource/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ResourceProjectsRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/_resource/expenses': {
      id: '/_resource/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ResourceExpensesRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/_resource/clients': {
      id: '/_resource/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ResourceClientsRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/_resource/projects/': {
      id: '/_resource/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ResourceProjectsIndexRouteImport
      parentRoute: typeof ResourceProjectsRoute
    }
    '/_resource/expenses/': {
      id: '/_resource/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ResourceExpensesIndexRouteImport
      parentRoute: typeof ResourceExpensesRoute
    }
    '/_resource/clients/': {
      id: '/_resource/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ResourceClientsIndexRouteImport
      parentRoute: typeof ResourceClientsRoute
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/expenses/$id': {
      id: '/api/expenses/$id'
      path: '/$id'
      fullPath: '/api/expenses/$id'
      preLoaderRoute: typeof ApiExpensesIdRouteImport
      parentRoute: typeof ApiExpensesRoute
    }
    '/api/clients/$id': {
      id: '/api/clients/$id'
      path: '/$id'
      fullPath: '/api/clients/$id'
      preLoaderRoute: typeof ApiClientsIdRouteImport
      parentRoute: typeof ApiClientsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resource/projects/create': {
      id: '/_resource/projects/create'
      path: '/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ResourceProjectsCreateRouteImport
      parentRoute: typeof ResourceProjectsRoute
    }
    '/_resource/expenses/create': {
      id: '/_resource/expenses/create'
      path: '/create'
      fullPath: '/expenses/create'
      preLoaderRoute: typeof ResourceExpensesCreateRouteImport
      parentRoute: typeof ResourceExpensesRoute
    }
    '/_resource/clients/create': {
      id: '/_resource/clients/create'
      path: '/create'
      fullPath: '/clients/create'
      preLoaderRoute: typeof ResourceClientsCreateRouteImport
      parentRoute: typeof ResourceClientsRoute
    }
    '/_resource/projects/edit/$id': {
      id: '/_resource/projects/edit/$id'
      path: '/edit/$id'
      fullPath: '/projects/edit/$id'
      preLoaderRoute: typeof ResourceProjectsEditIdRouteImport
      parentRoute: typeof ResourceProjectsRoute
    }
    '/_resource/projects/create/modal': {
      id: '/_resource/projects/create/modal'
      path: '/modal'
      fullPath: '/projects/create/modal'
      preLoaderRoute: typeof ResourceProjectsCreateModalRouteImport
      parentRoute: typeof ResourceProjectsCreateRoute
    }
    '/_resource/expenses/edit/$id': {
      id: '/_resource/expenses/edit/$id'
      path: '/edit/$id'
      fullPath: '/expenses/edit/$id'
      preLoaderRoute: typeof ResourceExpensesEditIdRouteImport
      parentRoute: typeof ResourceExpensesRoute
    }
    '/_resource/expenses/create/modal': {
      id: '/_resource/expenses/create/modal'
      path: '/modal'
      fullPath: '/expenses/create/modal'
      preLoaderRoute: typeof ResourceExpensesCreateModalRouteImport
      parentRoute: typeof ResourceExpensesCreateRoute
    }
    '/_resource/clients/edit/$id': {
      id: '/_resource/clients/edit/$id'
      path: '/edit/$id'
      fullPath: '/clients/edit/$id'
      preLoaderRoute: typeof ResourceClientsEditIdRouteImport
      parentRoute: typeof ResourceClientsRoute
    }
    '/_resource/clients/create/modal': {
      id: '/_resource/clients/create/modal'
      path: '/modal'
      fullPath: '/clients/create/modal'
      preLoaderRoute: typeof ResourceClientsCreateModalRouteImport
      parentRoute: typeof ResourceClientsCreateRoute
    }
    '/_resource/projects/edit/$id/modal': {
      id: '/_resource/projects/edit/$id/modal'
      path: '/modal'
      fullPath: '/projects/edit/$id/modal'
      preLoaderRoute: typeof ResourceProjectsEditIdModalRouteImport
      parentRoute: typeof ResourceProjectsEditIdRoute
    }
    '/_resource/expenses/edit/$id/modal': {
      id: '/_resource/expenses/edit/$id/modal'
      path: '/modal'
      fullPath: '/expenses/edit/$id/modal'
      preLoaderRoute: typeof ResourceExpensesEditIdModalRouteImport
      parentRoute: typeof ResourceExpensesEditIdRoute
    }
    '/_resource/clients/edit/$id/modal': {
      id: '/_resource/clients/edit/$id/modal'
      path: '/modal'
      fullPath: '/clients/edit/$id/modal'
      preLoaderRoute: typeof ResourceClientsEditIdModalRouteImport
      parentRoute: typeof ResourceClientsEditIdRoute
    }
  }
}

interface ResourceClientsCreateRouteChildren {
  ResourceClientsCreateModalRoute: typeof ResourceClientsCreateModalRoute
}

const ResourceClientsCreateRouteChildren: ResourceClientsCreateRouteChildren = {
  ResourceClientsCreateModalRoute: ResourceClientsCreateModalRoute,
}

const ResourceClientsCreateRouteWithChildren =
  ResourceClientsCreateRoute._addFileChildren(
    ResourceClientsCreateRouteChildren,
  )

interface ResourceClientsEditIdRouteChildren {
  ResourceClientsEditIdModalRoute: typeof ResourceClientsEditIdModalRoute
}

const ResourceClientsEditIdRouteChildren: ResourceClientsEditIdRouteChildren = {
  ResourceClientsEditIdModalRoute: ResourceClientsEditIdModalRoute,
}

const ResourceClientsEditIdRouteWithChildren =
  ResourceClientsEditIdRoute._addFileChildren(
    ResourceClientsEditIdRouteChildren,
  )

interface ResourceClientsRouteChildren {
  ResourceClientsCreateRoute: typeof ResourceClientsCreateRouteWithChildren
  ResourceClientsIndexRoute: typeof ResourceClientsIndexRoute
  ResourceClientsEditIdRoute: typeof ResourceClientsEditIdRouteWithChildren
}

const ResourceClientsRouteChildren: ResourceClientsRouteChildren = {
  ResourceClientsCreateRoute: ResourceClientsCreateRouteWithChildren,
  ResourceClientsIndexRoute: ResourceClientsIndexRoute,
  ResourceClientsEditIdRoute: ResourceClientsEditIdRouteWithChildren,
}

const ResourceClientsRouteWithChildren = ResourceClientsRoute._addFileChildren(
  ResourceClientsRouteChildren,
)

interface ResourceExpensesCreateRouteChildren {
  ResourceExpensesCreateModalRoute: typeof ResourceExpensesCreateModalRoute
}

const ResourceExpensesCreateRouteChildren: ResourceExpensesCreateRouteChildren =
  {
    ResourceExpensesCreateModalRoute: ResourceExpensesCreateModalRoute,
  }

const ResourceExpensesCreateRouteWithChildren =
  ResourceExpensesCreateRoute._addFileChildren(
    ResourceExpensesCreateRouteChildren,
  )

interface ResourceExpensesEditIdRouteChildren {
  ResourceExpensesEditIdModalRoute: typeof ResourceExpensesEditIdModalRoute
}

const ResourceExpensesEditIdRouteChildren: ResourceExpensesEditIdRouteChildren =
  {
    ResourceExpensesEditIdModalRoute: ResourceExpensesEditIdModalRoute,
  }

const ResourceExpensesEditIdRouteWithChildren =
  ResourceExpensesEditIdRoute._addFileChildren(
    ResourceExpensesEditIdRouteChildren,
  )

interface ResourceExpensesRouteChildren {
  ResourceExpensesCreateRoute: typeof ResourceExpensesCreateRouteWithChildren
  ResourceExpensesIndexRoute: typeof ResourceExpensesIndexRoute
  ResourceExpensesEditIdRoute: typeof ResourceExpensesEditIdRouteWithChildren
}

const ResourceExpensesRouteChildren: ResourceExpensesRouteChildren = {
  ResourceExpensesCreateRoute: ResourceExpensesCreateRouteWithChildren,
  ResourceExpensesIndexRoute: ResourceExpensesIndexRoute,
  ResourceExpensesEditIdRoute: ResourceExpensesEditIdRouteWithChildren,
}

const ResourceExpensesRouteWithChildren =
  ResourceExpensesRoute._addFileChildren(ResourceExpensesRouteChildren)

interface ResourceProjectsCreateRouteChildren {
  ResourceProjectsCreateModalRoute: typeof ResourceProjectsCreateModalRoute
}

const ResourceProjectsCreateRouteChildren: ResourceProjectsCreateRouteChildren =
  {
    ResourceProjectsCreateModalRoute: ResourceProjectsCreateModalRoute,
  }

const ResourceProjectsCreateRouteWithChildren =
  ResourceProjectsCreateRoute._addFileChildren(
    ResourceProjectsCreateRouteChildren,
  )

interface ResourceProjectsEditIdRouteChildren {
  ResourceProjectsEditIdModalRoute: typeof ResourceProjectsEditIdModalRoute
}

const ResourceProjectsEditIdRouteChildren: ResourceProjectsEditIdRouteChildren =
  {
    ResourceProjectsEditIdModalRoute: ResourceProjectsEditIdModalRoute,
  }

const ResourceProjectsEditIdRouteWithChildren =
  ResourceProjectsEditIdRoute._addFileChildren(
    ResourceProjectsEditIdRouteChildren,
  )

interface ResourceProjectsRouteChildren {
  ResourceProjectsCreateRoute: typeof ResourceProjectsCreateRouteWithChildren
  ResourceProjectsIndexRoute: typeof ResourceProjectsIndexRoute
  ResourceProjectsEditIdRoute: typeof ResourceProjectsEditIdRouteWithChildren
}

const ResourceProjectsRouteChildren: ResourceProjectsRouteChildren = {
  ResourceProjectsCreateRoute: ResourceProjectsCreateRouteWithChildren,
  ResourceProjectsIndexRoute: ResourceProjectsIndexRoute,
  ResourceProjectsEditIdRoute: ResourceProjectsEditIdRouteWithChildren,
}

const ResourceProjectsRouteWithChildren =
  ResourceProjectsRoute._addFileChildren(ResourceProjectsRouteChildren)

interface ResourceRouteChildren {
  ResourceClientsRoute: typeof ResourceClientsRouteWithChildren
  ResourceExpensesRoute: typeof ResourceExpensesRouteWithChildren
  ResourceProjectsRoute: typeof ResourceProjectsRouteWithChildren
}

const ResourceRouteChildren: ResourceRouteChildren = {
  ResourceClientsRoute: ResourceClientsRouteWithChildren,
  ResourceExpensesRoute: ResourceExpensesRouteWithChildren,
  ResourceProjectsRoute: ResourceProjectsRouteWithChildren,
}

const ResourceRouteWithChildren = ResourceRoute._addFileChildren(
  ResourceRouteChildren,
)

interface ApiClientsRouteChildren {
  ApiClientsIdRoute: typeof ApiClientsIdRoute
}

const ApiClientsRouteChildren: ApiClientsRouteChildren = {
  ApiClientsIdRoute: ApiClientsIdRoute,
}

const ApiClientsRouteWithChildren = ApiClientsRoute._addFileChildren(
  ApiClientsRouteChildren,
)

interface ApiExpensesRouteChildren {
  ApiExpensesIdRoute: typeof ApiExpensesIdRoute
}

const ApiExpensesRouteChildren: ApiExpensesRouteChildren = {
  ApiExpensesIdRoute: ApiExpensesIdRoute,
}

const ApiExpensesRouteWithChildren = ApiExpensesRoute._addFileChildren(
  ApiExpensesRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResourceRoute: ResourceRouteWithChildren,
  LoginRoute: LoginRoute,
  PdfRoute: PdfRoute,
  ApiClientsRoute: ApiClientsRouteWithChildren,
  ApiExchangeRatesRoute: ApiExchangeRatesRoute,
  ApiExpensesRoute: ApiExpensesRouteWithChildren,
  ApiPdfRoute: ApiPdfRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
